version: '3.4'
services:
  web:
    container_name: auth-server
    build: 
      context: ../
      dockerfile: ./Gts.AuthorizationServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - auth-server-dev
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
networks:
  auth-server-dev:
    driver: bridge